import { useEffect, useMemo, useRef, useState } from 'react';
import QRCode from 'qrcode';
import { BrowserMultiFormatReader } from '@zxing/browser';
import { Camera, Printer, QrCode, Search, X } from 'lucide-react';

type Product={id:number;code:string;name:string;unit:string;stock:number;min_stock:number;supplier:string|null;pack:string|null;last_entry:string|null};
type Props={products:Product[]; onScan:(code:string)=>void};
export const qrValue=(code:string)=>`FABRIKO|${code}`;
function QRImage({code,size=150}:{code:string;size?:number}){const[src,setSrc]=useState('');useEffect(()=>{let alive=true;QRCode.toDataURL(qrValue(code),{width:size,margin:2,errorCorrectionLevel:'M'}).then(v=>alive&&setSrc(v));return()=>{alive=false}},[code,size]);return src?<img src={src} width={size} height={size} alt={`QR ${code}`}/>:<div className="qr-loading">Generando QR…</div>}
export function QRScanner({onClose,onScan}:{onClose:()=>void;onScan:(code:string)=>void}){const video=useRef<HTMLVideoElement>(null);const reader=useRef<BrowserMultiFormatReader|null>(null);const[error,setError]=useState('');useEffect(()=>{const r=new BrowserMultiFormatReader();reader.current=r;let active=true;(async()=>{try{if(!video.current)return;await r.decodeFromConstraints({video:{facingMode:{ideal:'environment'}},audio:false},video.current,(result)=>{if(!active||!result)return;const raw=result.getText();const code=raw.startsWith('FABRIKO|')?raw.slice(8):raw;onScan(code);onClose()})}catch{setError('No fue posible abrir la cámara. Verifica el permiso del navegador.')}})();return()=>{active=false;r.reset()}},[onClose,onScan]);return <div className="overlay qr-overlay"><div className="modal qr-scanner-modal"><div className="panelhead"><div><h2><QrCode/> Escanear producto</h2><small>Apunta la cámara al código QR del producto</small></div><button onClick={onClose}><X/></button></div><div className="scanner-frame"><video ref={video} autoPlay playsInline muted/><span className="scan-corner top-left"/><span className="scan-corner top-right"/><span className="scan-corner bottom-left"/><span className="scan-corner bottom-right"/></div>{error&&<p className="scan-error">{error}</p>}<div className="form-actions"><button className="secondary" onClick={onClose}><X/> Cancelar</button></div></div></div>}
export default function QRModule({products,onScan}:Props){const[q,setQ]=useState('');const[scanner,setScanner]=useState(false);const[printingCode,setPrintingCode]=useState<string|null>(null);const filtered=useMemo(()=>products.filter(p=>`${p.code} ${p.name} ${p.supplier||''}`.toLowerCase().includes(q.toLowerCase())),[products,q]);const printOne=(code:string)=>{setPrintingCode(code);window.setTimeout(()=>window.print(),200)};const printAll=()=>{setPrintingCode(null);window.setTimeout(()=>window.print(),200)};return <section className="panel qr-module"><div className="panelhead qr-head"><div><h2><QrCode/> Códigos QR de productos</h2><small>Cada producto tiene un QR único enlazado con su código para registrar Entradas y Salidas.</small></div><div className="qr-head-actions"><button className="secondary" onClick={()=>setScanner(true)}><Camera/> Escanear QR</button><button className="primary" onClick={printAll}><Printer/> Imprimir todos</button></div></div><div className="qr-info"><QrCode size={22}/><div><b>Flujo rápido en celular</b><span>Escanea un QR → FABRIKO identifica el producto → registra Entrada o Salida → confirma el movimiento.</span></div></div><div className="filters"><div className="search"><Search size={17}/><input placeholder="Buscar producto o código..." value={q} onChange={e=>setQ(e.target.value)}/></div><span className="product-count">{filtered.length} productos</span></div><div className="qr-grid">{filtered.map(p=>{const number=products.findIndex(x=>x.id===p.id)+1;const isPrinting=printingCode===p.code;return <article className={`qr-card ${printingCode&&!isPrinting?'print-hide':''} ${isPrinting?'print-show':''}`} key={p.id}><div className="qr-number">No. {String(number).padStart(3,'0')}</div><QRImage code={p.code}/><h3>{p.code}</h3><b>{p.name}</b><span>{p.unit} · {p.pack||'Sin presentación'}</span><small>Stock: {p.stock}</small><button className="qr-print-btn" type="button" onClick={()=>printOne(p.code)}><Printer size={16}/> Imprimir etiqueta</button></article>})}</div>{scanner&&<QRScanner onClose={()=>setScanner(false)} onScan={onScan}/>}</section>}
